CREATE DATABASE FluxoVital;
USE FluxoVital;

CREATE TABLE Motorista
(
	ID_MOTORISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_MOTORISTA VARCHAR(50) NOT NULL,
    CPF_MOTORISTA CHAR(11) NOT NULL UNIQUE,
    CATEGORIA_CNH CHAR(2) NOT NULL,
    FOTO_PERFIL LONGBLOB 
);

CREATE TABLE TipoVeiculo(
	ID_TIPO_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
	NOME_TIPO_VEICULO VARCHAR(20) NOT NULL,
    MACA BOOL NOT NULL
);

CREATE TABLE StatusGeral(
	ID_STATUS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_STATUS VARCHAR(20) NOT NULL 
);

CREATE TABLE Veiculo(
	ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    ID_TIPO_VEICULO INT NOT NULL,
    ID_STATUS INT NOT NULL,
    CAPACIDADE INT NOT NULL,
    FOREIGN KEY (ID_TIPO_VEICULO) REFERENCES TipoVeiculo(ID_TIPO_VEICULO), 
    FOREIGN KEY (ID_STATUS) REFERENCES StatusGeral(ID_STATUS)
);

CREATE TABLE MotoristaVeiculo(
	ID_MOTORISTA_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
    ID_MOTORISTA INT NOT NULL,
    ID_VEICULO INT NOT NULL,
    DATA_HORA_EMPRESTIMO DATETIME NOT NULL,
    
    FOREIGN KEY (ID_MOTORISTA) REFERENCES Motorista(ID_MOTORISTA),
    FOREIGN KEY (ID_VEICULO) REFERENCES Veiculo(ID_VEICULO)
);

CREATE TABLE Estado(
	ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_ESTADO CHAR(2) NOT NULL 
);

CREATE TABLE Cidade(
	ID_CIDADE INT PRIMARY KEY AUTO_INCREMENT,
    ID_ESTADO INT NOT NULL,
    NOME_CIDADE VARCHAR(50) NOT NULL,
    
    FOREIGN KEY (ID_ESTADO) REFERENCES Estado(ID_ESTADO)
);

CREATE TABLE Bairro(
	ID_BAIRRO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CIDADE INT NOT NULL,
    NOME_BAIRRO VARCHAR(50) NOT NULL,
    
    FOREIGN KEY (ID_CIDADE) REFERENCES Cidade(ID_CIDADE) 
);

CREATE TABLE Rua(
	ID_RUA INT PRIMARY KEY AUTO_INCREMENT,
    ID_BAIRRO INT NOT NULL,
    NOME_RUA VARCHAR(50) NOT NULL,
    CEP CHAR(8) NOT NULL,
    
    FOREIGN KEY (ID_BAIRRO) REFERENCES Bairro (ID_BAIRRO)
);

CREATE TABLE Endereco(
	ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    ID_RUA INT NOT NULL,
    NUMERO_ENDERECO VARCHAR(10),
    LATITUDE DECIMAL(10, 8) NOT NULL,
    LONGITUDE DECIMAL(11, 8) NOT NULL,
	COMPLEMENTO VARCHAR(255),
    
    FOREIGN KEY (ID_RUA) REFERENCES Rua(ID_RUA)
);

CREATE TABLE LocalAtendimento(
	ID_LOCAL_ATENDIMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_ENDERECO INT NOT NULL,
    NOME_LOCAL_ATENDIMENTO VARCHAR(255) NOT NULL,
    
    FOREIGN KEY (ID_ENDERECO) REFERENCES Endereco (ID_ENDERECO)
);



CREATE TABLE Paciente(
	ID_PACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    ID_ENDERECO INT NOT NULL,
    SEXO ENUM("M", "F") NOT NULL,
    NOME_PACIENTE VARCHAR(255) NOT NULL,
    CPF_PACIENTE CHAR(11) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR(20),
    
    FOREIGN KEY (ID_ENDERECO) REFERENCES Endereco (ID_ENDERECO)
);

CREATE TABLE TipoConsulta (
	ID_TIPO_CONSULTA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICO_CONSULTA VARCHAR(255) NOT NULL
);

CREATE TABLE SolicitacaoConsulta(
	ID_SOLICITACAO_CONSULTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE INT NOT NULL,
    ID_TIPO_CONSULTA INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    ID_LOCAL_ATENDIMENTO INT NOT NULL,
    ID_STATUS INT NOT NULL,
    DATA_HORA_IDA DATETIME NOT NULL,
    DATA_HORA_RETORNO DATETIME,
    DATA_HORA_CONSULTA DATETIME NOT NULL, 
    DATA_HORA_SOLICITACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACOMPANHANTE BOOL NOT NULL,
    MACA BOOL NOT NULL,
    INFORMACOES_ADICIONAIS VARCHAR(255),
    
    FOREIGN KEY (ID_PACIENTE) REFERENCES Paciente(ID_PACIENTE),
    FOREIGN KEY (ID_TIPO_CONSULTA) REFERENCES TipoConsulta(ID_TIPO_CONSULTA),
    FOREIGN KEY (ID_ENDERECO) REFERENCES Endereco(ID_ENDERECO),
    FOREIGN KEY (ID_LOCAL_ATENDIMENTO) REFERENCES LocalAtendimento(ID_LOCAL_ATENDIMENTO),
    FOREIGN KEY (ID_STATUS) REFERENCES StatusGeral(ID_STATUS)
);

CREATE TABLE PassageiroVeiculo(
	ID_PASSAGEIRO_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
    ID_VEICULO INT NOT NULL,
    ID_SOLICITACAO_CONSULTA INT NOT NULL,
    
    FOREIGN KEY (ID_VEICULO) REFERENCES Veiculo(ID_VEICULO),
    FOREIGN KEY (ID_SOLICITACAO_CONSULTA) REFERENCES SolicitacaoConsulta(ID_SOLICITACAO_CONSULTA)
);

CREATE TABLE Parada(
	ID_PARADA INT PRIMARY KEY AUTO_INCREMENT,
    ID_VEICULO INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    TIPO_PARADA ENUM("COLETA", "ENTREGA") NOT NULL,
    DATA_ROTA DATE NOT NULL,
    HORA_PARADA TIME,
    
    FOREIGN KEY (ID_VEICULO) REFERENCES Veiculo(ID_VEICULO),
    FOREIGN KEY (ID_PACIENTE) REFERENCES Paciente(ID_PACIENTE),
    FOREIGN KEY (ID_ENDERECO) REFERENCES Endereco(ID_ENDERECO)	
);

CREATE TABLE NivelAcesso(
	ID_NIVEL_ACESSO INT PRIMARY KEY AUTO_INCREMENT,
    NIVEL_ACESSO VARCHAR(30) NOT NULL
 );

CREATE TABLE Funcionario(
	ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_NIVEL_ACESSO INT NOT NULL,
    NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
    CPF_FUNCIONARIO CHAR(11) NOT NULL,
    DATA_NASCIMENTO_FUNCIONARIO DATE NOT NULL, 
    TELEFONE VARCHAR(20) NOT NULL,
    
    FOREIGN KEY (ID_NIVEL_ACESSO) REFERENCES NivelAcesso(ID_NIVEL_ACESSO)
);