SELECT 
    p.HORA_PARADA,
    pac.NOME_PACIENTE,
    pac.CPF_PACIENTE,
    tv.NOME_TIPO_VEICULO,
    v.PLACA,
    COALESCE(tc.DESCRICO_CONSULTA, 'Consulta') as TIPO_CONSULTA
FROM Parada p
JOIN Veiculo v ON p.ID_VEICULO = v.ID_VEICULO
JOIN TipoVeiculo tv ON v.ID_TIPO_VEICULO = tv.ID_TIPO_VEICULO
JOIN Paciente pac ON p.ID_PACIENTE = pac.ID_PACIENTE
LEFT JOIN SolicitacaoConsulta sc ON sc.ID_PACIENTE = pac.ID_PACIENTE 
     AND DATE(sc.DATA_HORA_IDA) = p.DATA_ROTA
LEFT JOIN TipoConsulta tc ON sc.ID_TIPO_CONSULTA = tc.ID_TIPO_CONSULTA
WHERE p.DATA_ROTA = %s 
  AND p.TIPO_PARADA = 'COLETA'