SELECT DISTINCT v.ID_VEICULO, v.PLACA, tv.NOME_TIPO_VEICULO
FROM Parada p
JOIN Veiculo v ON p.ID_VEICULO = v.ID_VEICULO
JOIN TipoVeiculo tv ON v.ID_TIPO_VEICULO = tv.ID_TIPO_VEICULO
WHERE p.DATA_ROTA = %s
ORDER BY v.ID_VEICULO;