INSERT INTO SolicitacaoConsulta (
    ID_PACIENTE, ID_TIPO_CONSULTA, ID_ENDERECO, ID_LOCAL_ATENDIMENTO, 
    ID_STATUS, DATA_HORA_IDA, DATA_HORA_RETORNO, DATA_HORA_CONSULTA, 
    ACOMPANHANTE, MACA, INFORMACOES_ADICIONAIS
) VALUES (
    %s, %s, %s, %s,
    %s, %s, %s, %s,
    %s, %s, %s
);